
from FreeCAD import Base
import FreeCAD as App
import BOPTools.JoinFeatures
import Part
import Part,PartGui
import Mesh
import sys


from base_case import build_base_case
from top_case import build_top_case

import importlib

importlib.reload(sys.modules['base_case'])
importlib.reload(sys.modules['top_case'])
# this is the maximum height needed inside the case
MAX_HEIGHT = 18

# this is the thickness of the curved base
PLATE_THICKNESS = 10

# this is the thickness of the base once the inset has been cut out
FLOOR_THICKNESS = 3


# the top of the base is a location 0,0,0
# the lowest edge of the base is at -10 in the centre

# the total height is 3 + 18 + 3 + 3 = 27 which is floor thickness + the cavity height + the thickness of the lid + the thickness of the panel

COLLAR_MAJOR_RADIUS = 350
COLLAR_MINOR_RADIUS = 140 
COLLAR_WIDTH = 50

PLATE_LENGTH = 128+20 + 20 


LIPO_WIDTH = 60+2
LIPO_LENGTH = 40
CAVITY_HEIGHT = 10 


CHIP_WIDTH = 88
CHIP_LENGTH = 48
CHIP_HEIGHT = 13


SEAL_LENGTH = CHIP_LENGTH+3+4
SEAL_WIDTH =  CHIP_WIDTH+5


bwb = SEAL_WIDTH + 4+ 4   # battery length bottom
blb = 50  # battery width bottom
bwt = SEAL_WIDTH + 4+ 4  # battery length top
blt = SEAL_LENGTH + 4 + 4 # battery width top


PANEL_WIDTH = 65
PANEL_LENGTH = 65
PANEL_HEIGHT = 3

slb = blt + 4.5 #6 # sodaq length bottom = battery length top
swb = bwt + 8 # sodaq width bottom
slt2 = PANEL_LENGTH + 6

swt2 = PANEL_WIDTH + 6 # 24 +GROW

SCREW_LOCATION_W = 83 # PANEL_WIDTH + 13 # 24 +GROW
SCREW_LOCATION_L = 63 # PANEL_LENGTH + 8 


doc = App.activeDocument()

def clean():
    objs = doc.Objects
    for obj in objs:
        name = obj.Name
        doc.removeObject(name)

def main():
    doc = App.activeDocument()
    clean()
    basecase = build_base_case(doc)
    topcase = build_top_case(doc)


    raise Exception("Stopping here")

















if __name__ == "__main__":
    main()












































































gripperbox1 = doc.addObject("Part::Box", "gripperbox1")
gripperbox1.Length = 7
gripperbox1.Width = 10
gripperbox1.Height = 13
gripperbox1.Placement = App.Placement(App.Vector(-30,-24,4.6),App.Rotation(App.Vector(1,0,0),0)) 




gripperbox2 = doc.addObject("Part::Box", "gripperbox2")
gripperbox2.Length = 30
gripperbox2.Width = 4
gripperbox2.Height = 6
gripperbox2.Placement = App.Placement(App.Vector(-15,39,4.6),App.Rotation(App.Vector(1,0,0),0)) 



fusion = doc.addObject("Part::MultiFuse","fusion")
doc.fusion.Shapes = [arduinobox2,gripperbox1,gripperbox2]
doc.recompute()

arduinobox =doc.addObject("Part::Feature","arduinobox")

arduinobox .Shape=Part.Solid(Part.Shell(fusion.Shape.Faces))

doc.removeObject(fusion.Label)

doc.removeObject('arduinobox2')
#doc.removeObject('marker1')
#doc.removeObject('marker2')
doc.removeObject('gripperbox1')
doc.removeObject('gripperbox2')

doc.recompute()

#arduinobox = doc.addObject('Part::Feature','arduinobox')
#arduinobox.Shape=doc.arduinobox2.Shape.removeSplitter()
#arduinobox.Label="arduinobox"

#doc.removeObject(arduinobox2.Label)

#doc.recompute()


#FreeCADGui.getDocument("Unnamed").getObject("arduinobox2").Transparency = 40
#FreeCADGui.getDocument("Unnamed").getObject("baseplate2").Transparency = 40

